/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include<stdint.h>

typedef volatile unsigned int v_uint_t ;
#define RCC_BASE        0x40021000
#define GPIOA_BASE 		0x40010800

#define RCC_APB2ENR       *((volatile uint32_t *)( RCC_BASE+0x18 ))
#define GPIO_CRH          *((volatile uint32_t *)( GPIOA_BASE+0x04))
#define GPIO_ODR          *((volatile uint32_t *)(GPIOA_BASE+0x0C))


typedef union{
	v_uint_t all_fields ;
	struct {
		v_uint_t reserved : 13 ;
		v_uint_t pin_13 : 1    ;

	}pins;
}R_ODR_t;


volatile R_ODR_t* R_ODR =  (volatile R_ODR_t*)(GPIOA_BASE + 0x0C) ;

int main(void)
{
	RCC_APB2ENR |= 1<<2 ;
	GPIO_CRH &= 0xff0fffff ;
	GPIO_CRH |= 0x00200000 ;

	while(1)
	{
		R_ODR->pins.pin_13 = 1 ;
		for(int i=0 ; i<5000 ; i++)
			R_ODR->pins.pin_13 = 0 ;


	}
}
